### ISSUE TITLE
e coli does not grow in "0_getting_started.ipynb"

### ISSUE THREAD

**Issue by matthpich** [segrelab/COMETS_Protocols#2]
Hi,
Is it expected that e_coli does not grow in "0_getting_started.ipynb"?
Thanks a lot for your help (and your great tool)!

**Comment by dukovski** [comment]
No, will not grow since all of the media are set to zero concentration. To make it grow you need to add the lines:

# Add 11mM glucose and remove o2
my_layout.set_specific_metabolite('glc__D_e', 0.011)
my_layout.set_specific_metabolite('o2_e', 0)

# Add the rest of nutrients unlimited (ammonia, phosphate, water and protons)
my_layout.set_specific_metabolite('nh4_e',1000);
my_layout.set_specific_metabolite('pi_e',1000);
my_layout.set_specific_metabolite('h2o_e',1000);
my_layout.set_specific_metabolite('h_e',1000);

before running the simulation. 
I think you are right, this should've been included. It was not because this protocol was meant to be just an intro to the actual run for the well-mixed test_tube.
